Connect to Google Drive

In [1]:
from google.colab import drive
import pandas as pd

# Mount to Google Drive
drive.mount('/content/drive')

Mounted at /content/drive

Load GROUND TRUTH into dataframe

In [17]:
# Provide full path to allstar CSV file in Google Drive
csv_path_allstar = '/content/drive/MyDrive/COMP 333/NBA-Data/NBA All Star Players and Stats 1980-2022.csv'

# Load the CSV file into a DataFrame
df_allstar = pd.read_csv(csv_path_allstar)

# Print out the schema
print("DataFrame Schema:")
display(df_allstar.info())

# Display the number of null values in each feature
null_counts = df_allstar.isnull().sum()
print("Number of Null Values in Each Feature:")
print(null_counts)

# Display the number of rows and columns
num_rows, num_columns = df_allstar.shape
print("Number of Rows:", num_rows)
print("Number of Columns:", num_columns)

DataFrame Schema:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1003 entries, 0 to 1002
Data columns (total 24 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   first         1003 non-null   object
 1   last          1003 non-null   object
 2   team          1003 non-null   object
 3   year          1003 non-null   int64
 4   games_played  1002 non-null   float64
 5   min           1002 non-null   object
 6   fgm           1002 non-null   float64
 7   fga           1002 non-null   float64
 8   fg3m          1002 non-null   float64
 9   fg3a          1002 non-null   float64
 10  ftm           1002 non-null   float64
 11  fta           1002 non-null   float64
 12  oreb          1002 non-null   float64
 13  dreb          1002 non-null   float64
 14  reb           1002 non-null   float64
 15  ast           1002 non-null   float64
 16  stl           1002 non-null   float64
 17  blk           1002 non-null   float64
 18  turnover      1002 non-null   float64
 19  pf            1002 non-null   float64
 20  pts           1002 non-null   float64
 21  fg_pct        1002 non-null   float64
 22  fg3_pct       1002 non-null   float64
 23  ft_pct        1002 non-null   float64
dtypes: float64(19), int64(1), object(4)
memory usage: 188.2+ KB

None

Number of Null Values in Each Feature:
first           0
last            0
team            0
year            0
games_played    1
min             1
fgm             1
fga             1
fg3m            1
fg3a            1
ftm             1
fta             1
oreb            1
dreb            1
reb             1
ast             1
stl             1
blk             1
turnover        1
pf              1
pts             1
fg_pct          1
fg3_pct         1
ft_pct          1
dtype: int64
Number of Rows: 1003
Number of Columns: 24

Load df_combined_cleaned into df

In [18]:
# Provide full path to df_combined_cleaned CSV file in Google Drive
df_combined_cleaned = '/content/drive/MyDrive/COMP 333/NBA-Data/df_combined_cleaned.csv'

# Load the CSV file into a DataFrame
df_combined_cleaned = pd.read_csv(df_combined_cleaned, sep=',')

df_combined_cleaned

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,2,Tariq Abdul-Wahad,SG,23,SAC,59,16,16.3,2.4,6.1,...,0.7,1.2,2.0,0.9,0.6,0.2,1.1,1.4,6.4,1997-1998
1,3,Shareef Abdur-Rahim,SF,21,VAN,82,82,36.0,8.0,16.4,...,2.8,4.3,7.1,2.6,1.1,0.9,3.1,2.5,22.3,1997-1998
2,4,Cory Alexander,PG,24,TOT,60,22,21.6,2.9,6.7,...,0.3,2.2,2.4,3.5,1.2,0.2,1.9,1.6,8.1,1997-1998
3,5,Ray Allen,SG,22,MIL,82,82,40.1,6.9,16.0,...,1.5,3.4,4.9,4.3,1.4,0.1,3.2,3.0,19.5,1997-1998
4,6,Derek Anderson,SF,23,CLE,66,13,27.9,3.6,8.9,...,0.8,2.0,2.8,3.4,1.3,0.2,1.9,2.1,11.7,1997-1998
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7804,601,Thaddeus Young,PF,33,TOT,52,1,16.3,2.7,5.2,...,1.5,2.5,4.0,2.0,1.0,0.3,1.0,1.6,6.2,2021-2022
7805,602,Trae Young,PG,23,ATL,76,76,34.9,9.4,20.3,...,0.7,3.1,3.7,9.7,0.9,0.1,4.0,1.7,28.4,2021-2022
7806,603,Omer Yurtseven,C,23,MIA,56,12,12.6,2.3,4.4,...,1.5,3.7,5.3,0.9,0.3,0.4,0.7,1.5,5.3,2021-2022
7807,20,Deni Avdija,SF,21,WAS,82,8,24.2,3.0,7.1,...,0.6,4.5,5.2,2.0,0.7,0.5,1.1,2.3,8.4,2021-2022
7808,22,Deandre Ayton,C,23,PHO,58,58,29.5,7.6,12.0,...,2.6,7.7,10.2,1.4,0.7,0.7,1.6,2.4,17.2,2021-2022

Schema integration on the allstart df

In [19]:
# Create a new "player" column by concatenating "first" and "last"
df_allstar['Player'] = df_allstar['first'] + ' ' + df_allstar['last']

# Drop the original "first" and "last" columns
df_allstar_modified = df_allstar.drop(['first', 'last'], axis=1)

# Specify columns to keep in the all-star table
columns_to_keep = ['Player', 'year']

# Drop all columns except the ones specified in columns_to_keep
df_allstar_modified = df_allstar_modified[columns_to_keep]
df_allstar_modified

                 Player  year
0         Julius Erving  1980
1         Eddie Johnson  1980
2         Artis Gilmore  1980
3          Reggie Theus  1980
4            Larry Bird  1980
...                 ...   ...
998         Paul George  2022
999     Anthony Edwards  2022
1000  Tyrese Haliburton  2022
1001       De'Aaron Fox  2022
1002  Jaren Jackson Jr.  2022

[1003 rows x 2 columns]

Add All-Star feature to df_combined_cleaned

In [20]:
# Convert 'year' column to string
df_allstar_modified['year'] = df_allstar_modified['year'].astype(str)

# Create a set of unique player and year combinations
all_star_set = set((player.lower().replace(" ", ""), year) for player, year in zip(df_allstar_modified['Player'], df_allstar_modified['year']))

# Add All-Star (GROUND TRUTH) by checking if the player and second year match in the all_star_set
#df_combined_cleaned['All-Star'] = df_combined_cleaned.apply(lambda row: (row['Player'], row['Year'][-4:]) in all_star_set, axis=1)
df_combined_cleaned['All-Star'] = df_combined_cleaned.apply(lambda row: (row['Player'].lower().replace(" ", ""), row['Year'][-4:]) in all_star_set, axis=1)

print(df_combined_cleaned)

# Count the number of 'All-Star' players
all_star_count = df_combined_cleaned['All-Star'].sum()

print("Number of 'All-Star' players:", all_star_count)

all_star_rows = df_combined_cleaned[df_combined_cleaned['All-Star']]
print(all_star_rows)

       Rk               Player Pos  Age   Tm   G  GS    MP   FG   FGA  ...  \
0       2    Tariq Abdul-Wahad  SG   23  SAC  59  16  16.3  2.4   6.1  ...
1       3  Shareef Abdur-Rahim  SF   21  VAN  82  82  36.0  8.0  16.4  ...
2       4       Cory Alexander  PG   24  TOT  60  22  21.6  2.9   6.7  ...
3       5            Ray Allen  SG   22  MIL  82  82  40.1  6.9  16.0  ...
4       6       Derek Anderson  SF   23  CLE  66  13  27.9  3.6   8.9  ...
...   ...                  ...  ..  ...  ...  ..  ..   ...  ...   ...  ...
7804  601       Thaddeus Young  PF   33  TOT  52   1  16.3  2.7   5.2  ...
7805  602           Trae Young  PG   23  ATL  76  76  34.9  9.4  20.3  ...
7806  603       Omer Yurtseven   C   23  MIA  56  12  12.6  2.3   4.4  ...
7807   20          Deni Avdija  SF   21  WAS  82   8  24.2  3.0   7.1  ...
7808   22        Deandre Ayton   C   23  PHO  58  58  29.5  7.6  12.0  ...

      DRB   TRB  AST  STL  BLK  TOV   PF   PTS       Year  All-Star
0     1.2   2.0  0.9  0.6  0.2  1.1  1.4   6.4  1997-1998     False
1     4.3   7.1  2.6  1.1  0.9  3.1  2.5  22.3  1997-1998     False
2     2.2   2.4  3.5  1.2  0.2  1.9  1.6   8.1  1997-1998     False
3     3.4   4.9  4.3  1.4  0.1  3.2  3.0  19.5  1997-1998     False
4     2.0   2.8  3.4  1.3  0.2  1.9  2.1  11.7  1997-1998     False
...   ...   ...  ...  ...  ...  ...  ...   ...        ...       ...
7804  2.5   4.0  2.0  1.0  0.3  1.0  1.6   6.2  2021-2022     False
7805  3.1   3.7  9.7  0.9  0.1  4.0  1.7  28.4  2021-2022     False
7806  3.7   5.3  0.9  0.3  0.4  0.7  1.5   5.3  2021-2022     False
7807  4.5   5.2  2.0  0.7  0.5  1.1  2.3   8.4  2021-2022     False
7808  7.7  10.2  1.4  0.7  0.7  1.6  2.4  17.2  2021-2022     False

[7809 rows x 32 columns]
Number of 'All-Star' players: 524
       Rk            Player   Pos  Age   Tm   G  GS    MP   FG   FGA  ...  \
298     4         Ray Allen    SG   23  MIL  50  50  34.4  6.1  13.5  ...
319    50       Kobe Bryant    SG   20  LAL  50  50  37.9  7.2  15.6  ...
326    63      Vince Carter    SF   22  TOR  50  49  35.2  6.9  15.3  ...
350   111        Tim Duncan    PF   22  SAS  50  50  39.3  8.4  16.9  ...
357   123    Michael Finley    SF   25  DAL  50  50  41.0  7.8  17.5  ...
...   ...               ...   ...  ...  ...  ..  ..   ...  ...   ...  ...
7729  467     Julius Randle    PF   27  NYK  72  72  35.3  7.1  17.3  ...
7743  488  Domantas Sabonis  C-PF   25  TOT  62  61  34.5  7.1  12.5  ...
7744  488  Domantas Sabonis     C   25  IND  47  46  34.7  7.0  12.1  ...
7750  501     Pascal Siakam    PF   27  TOR  68  68  37.9  8.8  17.8  ...
7762  526      Jayson Tatum    SF   23  BOS  76  76  35.9  9.3  20.6  ...

      DRB   TRB  AST  STL  BLK  TOV   PF   PTS       Year  All-Star
298   3.1   4.2  3.6  1.1  0.1  2.4  2.3  17.1  1998-1999      True
319   4.2   5.3  3.8  1.4  1.0  3.1  3.1  19.9  1998-1999      True
326   3.8   5.7  3.0  1.1  1.5  2.2  2.8  18.3  1998-1999      True
350   8.2  11.4  2.4  0.9  2.5  2.9  2.9  21.7  1998-1999      True
357   3.9   5.3  4.4  1.3  0.3  2.1  1.9  20.2  1998-1999      True
...   ...   ...  ...  ...  ...  ...  ...   ...        ...       ...
7729  8.2   9.9  5.1  0.7  0.5  3.4  2.8  20.1  2021-2022      True
7743  8.9  12.1  5.2  1.0  0.4  3.1  3.3  18.9  2021-2022      True
7744  8.8  12.1  5.0  1.0  0.5  3.0  3.1  18.9  2021-2022      True
7750  6.6   8.5  5.3  1.3  0.6  2.7  3.3  22.8  2021-2022      True
7762  6.9   8.0  4.4  1.0  0.6  2.9  2.3  26.9  2021-2022      True

[524 rows x 32 columns]

Find how many unique all star players there are

In [21]:
all_star_players = set(player.lower().replace(" ", "") for player in all_star_rows['Player'])

# Print the count of unique players
print(len(all_star_players))

147

Keep all star players most recent year and for any NON-All start players we keep their most recent year.

In [26]:
# Make copy
df_combined_copy = df_combined_cleaned.copy()

# Filter to keep only All-Star rows
all_star_rows = df_combined_copy[df_combined_copy['All-Star']]

# Sort the dataframe by 'Year' in descending order for each player group
all_star_most_recent = all_star_rows.sort_values(by='Year', ascending=False).groupby('Player').first().reset_index()

# Filter to keep only non All-Star rows
non_all_star_rows = df_combined_cleaned[~df_combined_cleaned['All-Star']]

df_sorted_by_year = non_all_star_rows.sort_values(by = ['Year', 'G'], ascending = [False, False])

df_grouped_by_player = df_sorted_by_year.groupby(['Player'])

non_all_star_most_recent = df_grouped_by_player.first().reset_index()

# Get the list of players in all_star_most_recent
all_star_players = all_star_most_recent['Player'].tolist()

# Filter out players in non_all_star_most_recent that are also in all_star_most_recent
filtered_non_all_star_most_recent = non_all_star_most_recent[~non_all_star_most_recent['Player'].isin(all_star_players)]

# Concatenate the All-Star and non All-Star most recent rows
final_df = pd.concat([all_star_most_recent, filtered_non_all_star_most_recent])

print(final_df)

                             Player   Rk    Pos  Age   Tm   G  GS    MP   FG  \
0                        Al Horford  204      C   30  BOS  68  68  32.3  5.6
1                     Allan Houston  181     SG   28  NYK  82  82  38.6  7.5
2                     Allen Iverson  203     SG   32  DEN  82  82  41.8  8.7
3                   Alonzo Mourning  269      C   28  MIA  46  46  38.1  7.0
4                 Amar'e Stoudemire  377     PF   27  PHO  82  82  34.6  8.6
...                             ...  ...    ...  ...  ...  ..  ..   ...  ...
1479                ÃÂlex Abrines    1     SG   24  OKC  75   8  15.1  1.5
1480                ÃÂscar Torres  400     SG   25  HOU  65  13  16.5  2.1
1481  ÃÂ arÃÂ«nas JasikeviÃÂius  211  SG-PG   30  TOT  63   3  15.4  2.0
1482                   ÃÂ½an Tabak  381      C   27  TOT  57  34  17.3  2.5
1483          ÃÂ½arko ÃÂabarkapa   69     PF   24  GSW  61   0   8.3  1.1

       FGA  ...  DRB   TRB  AST  STL  BLK  TOV   PF   PTS       Year  All-Star
0     11.8  ...  5.4   6.8  5.0  0.8  1.3  1.7  2.0  14.0  2016-2017      True
1     15.5  ...  2.8   3.3  2.7  0.8  0.2  2.3  2.7  19.7  1999-2000      True
2     19.0  ...  2.4   3.0  7.1  2.0  0.1  3.0  1.3  26.4  2007-2008      True
3     13.8  ...  7.4  11.0  1.6  0.7  3.9  3.0  3.5  20.1  1998-1999      True
4     15.4  ...  6.1   8.9  1.0  0.6  1.0  2.6  3.4  23.1  2009-2010      True
...    ...  ...  ...   ...  ...  ...  ...  ...  ...   ...        ...       ...
1479   3.9  ...  1.2   1.5  0.4  0.5  0.1  0.3  1.7   4.7  2017-2018     False
1480   5.2  ...  1.2   1.9  0.6  0.4  0.1  0.8  1.0   6.0  2001-2002     False
1481   5.1  ...  0.9   1.1  2.7  0.4  0.0  1.4  1.2   6.1  2006-2007     False
1482   5.3  ...  2.2   3.7  0.8  0.4  0.7  1.1  2.9   5.4  1997-1998     False
1483   2.9  ...  1.2   1.8  0.3  0.2  0.1  0.6  1.4   3.3  2005-2006     False

[1485 rows x 32 columns]

Save DataFrame to Google Drive

In [15]:
final_df_file_path = '/content/drive/MyDrive/COMP 333/NBA-Data/final_df.csv'
final_df.to_csv(final_df_file_path, index=False)

Random statistic: Count the all stars that we cannot retrieve since our main dataset starts at 1997 and not 1980

In [12]:
all_star_1980_to_1997 = df_allstar[(df_allstar['year'] >= 1980) & (df_allstar['year'] <= 1997)]

# Count the number of unique All-Star players
num_all_star_1980_to_1997 = all_star_1980_to_1997['Player'].nunique()

# Print the result
print("Number of All-Star players from 1980 to 1997:", num_all_star_1980_to_1997)

Number of All-Star players from 1980 to 1997: 133